### ISSUE TITLE
Registry system for documentation and validation of YAML fields

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/ymlthis#16]
Packages could use this to formally specify and document their YAML fields, e.g.

`register_toplevel_yaml(data.frame(field = "type", validate = pkg::is_function(), doc = "This is what this does"))`

Save to an environment yamlthis checks for somehow?

**Comment by malcolmbarrett** [comment]
This needs to marinate, but here are a few thoughts after discussing with @rich-iannone:

* maybe should be a separate package (something lightweight)
* maybe have packages write this as YAML, e.g.

```yaml
pkg: pkgname
x:
  y: 
    z: []
    yml_validate: is.numeric
    yml_desc: this is what z is 
    yml_validate_order: true # check that z is after y is after x
```

* if using this approach, have some syntax? e.g. `yml_validate: ~ is.numeric(.x) && ~length(.x) == 1`
* how to store and retrieve?
*  A completely different approach is to have helper functions to create function factories for packages in the format ymlthis_pkgname() that’s  has internal validation etc.
