### ISSUE TITLE
[QUESTION] How to set below yaml using `yml_latex_opts` ?

### ISSUE THREAD

**Issue by alienzj** [r-lib/ymlthis#89]
Basically below is what I want:
```yaml
mainfont: "NotoSerif-VF.ttf"
mainfontoptions:
  - Path=/path/to/fontdir
  - Scale=MatchUppercase
```

I tried this:
```r
yml_latex_opts(
    mainfont = "NotoSerif-VF.ttf",
    mainfontoptions = list(
        "Path" = fonts_dir,
        "Scale" = "MatchUppercase"
    )
```

It generated below yaml:
```yaml
mainfont: "NotoSerif-VF.ttf"
mainfontoptions:
  Path: /path/to/fontdir
  Scale: MatchUppercase
```
 
Anyone can help me?
Thanks a lot!
